# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/quarto-blog',
                'doc_host': 'https://Ekamjot-Kaire.github.io',
                'git_url': 'https://github.com/Ekamjot-Kaire/quarto-blog',
                'lib_path': 'quarto_blog'},
  'syms': {'quarto_blog.core': {'quarto_blog.core.foo': ('core.html#foo', 'quarto_blog/core.py')}}}
